### ISSUE TITLE
play.go example not working

### ISSUE THREAD

**Issue by mixedCase** [gordonklaus/portaudio#14]
Tried with several files, none works. In case it's not my files, a sample for testing would be a useful addition.

**Comment by gordonklaus** [comment]
It should work with files produced by the `record.go` example.  I don't know if I ever tried with anything else.

**Comment by mixedCase** [comment]
I can confirm it works with files produced by `record.go`. I can't get it to work with other files when tweaking the parameters but I'll close this as I can't conclude it's not user error.
