### ISSUE TITLE
Go signal killed when run examples on macOS

### ISSUE THREAD

**Issue by cmingxu** [gordonklaus/portaudio#19]
Hi

After compile portaudio on my MacOS and run any program under examples directory. I always go signal killed output.

Any ideas?

**Comment by gordonklaus** [comment]
Can you provide the exact output you are seeing?

What version of Go and PortAudio are you using?

This sounds familiar, it may have been fixed in a point release (1.8.3?).  Try updating Go if you don't have the latest.  1.8.3 works for me (I haven't tried 1.9 yet).
