### ISSUE TITLE
Can't compile for ARM on OSX

### ISSUE THREAD

**Issue by plutov** [gordonklaus/portaudio#21]
I want to compile Go program on Mac and execute it later on Raspberry Pi (ARM arch), I ma using this way:
```
CGO_ENABLED=1 GOARCH=arm GOOS=linux go build -o culture-bot-rpi rpi-test/main.go
# runtime/cgo
clang: error: argument unused during compilation: '-mno-thumb' [-Werror,-Wunused-command-line-argument]
```

Is there a way to be able to compile it?

**Comment by Edwin-Luijten** [comment]
Having the same but on linux:
```
GOARM=7 GOARCH=arm GOOS=linux go build -o ${build_dir}/mic-arm ./main.go
```
build constraints exclude all Go files in /home/edwin/go/pkg/mod/github.com/gordonklaus/portaudio@v0.0.0-20180817120803-00e7307ccd93

**Comment by gordonklaus** [comment]
@Edwin-Luijten The `build constraints exclude all Go files in ...` error you're seeing is due to `cgo` being disable by default during cross-compilation, as portaudio.go requires cgo.  You have to enable it by setting `CGO_ENABLED=1`.  But then you'll need a cross-compiling C compiler.  Or try [xgo](https://github.com/karalabe/xgo).

**Comment by BigB84** [comment]
Maybe it's time for docker? 
You may be interested in [this](https://dh1tw.de/2019/12/cross-compiling-golang-cgo-projects/) step-by-step tutorial _which really helped me._

According to above, You could create `golang:1.17-bullseye` Dockerfile with architecture and compiler (for windows / linux) of your choice  _(as debian bullseye has multiarch support and multiarch libs)_  
However be careful with musl (glib alternative) lib linux distros like alpine linux according to [this](https://unix.stackexchange.com/questions/666559/crosscompile-golang-app-with-docker-for-alpine-linux-musl-aarch64-with-nativ)
