### ISSUE TITLE
Hou would I record a 16bit 16khz pcm with this lib?

### ISSUE THREAD

**Issue by aldarionsevero** [gordonklaus/portaudio#22]

**Comment by gordonklaus** [comment]
You can do this with only small modifications to [examples/record.go](examples/record.go).

**Comment by gordonklaus** [comment]
@adneg You should be able to change `int32` on [this line](https://github.com/gordonklaus/portaudio/blob/master/examples/record.go#L70) to `int16` and `44100` to `8000` on the next line to get the format you want.  And then:

```
enc, err := g711.NewUlawEncoder(w, g711.Lpcm)
binary.Write(enc, binary.BigEndian, in)
```

although I'm not sure about the endianness.

I don't know why your `play` command is quiet.  Are you sure your microphone is working?  Have you tried the command with a known good file?

**Comment by adneg** [comment]
I have to do something wrong
but I do not know what. 

`package main

import (
	"encoding/binary"
	//"fmt"
	"os"
	"os/signal"
	//"strings"

	"github.com/gordonklaus/portaudio"
)

func main() {
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, os.Interrupt, os.Kill)

	fileName := "test.raw"

	f, err := os.Create(fileName)
	chk(err)

	portaudio.Initialize()
	defer portaudio.Terminate()
	in := make([]int16, 64)
	stream, err := portaudio.OpenDefaultStream(1, 0, 44100, len(in), in)
	chk(err)
	defer stream.Close()

	chk(stream.Start())
	for {
		chk(stream.Read())
		chk(binary.Write(f, binary.BigEndian, in))
		//nSamples += len(in)
		select {
		case <-sig:
			return
		default:
		}
	}
	chk(stream.Stop())
}

func chk(err error) {
	if err != nil {
		panic(err)
	}
}`

my  test.raw is 1 channel 16-bit 44100Hz.
i play:
`play -t raw -r 44100 -e signed -b 16 -c 1 test.raw` 

`test.raw:

 File Size: 971k      Bit Rate: 706k
  Encoding: Signed PCM    
  Channels: 1 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:11.00  
`
and is only nois .
hmmm
but when  change
in record.go lines:
`
chk(binary.Write(f, binary.BigEndian, int16(16)))                  //bits per sample
`
and
`     in := make([]int16, 64)
	stream, err := portaudio.OpenDefaultStream(1, 0, 44100, len(in), in)
`
recrod file and
next a play:

`
play test.aiff 

test.aiff:

 File Size: 185k      Bit Rate: 353k
  Encoding: Signed PCM    
  Channels: 1 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:04.20  

In:50.0% 00:00:02.10 [00:00:02.10] Out:92.6k [      |      ] Hd:0.0 Clip:0    
Done.

`

I hear what I was saying.

hmmm why is there different Bit Rate.

**Comment by gordonklaus** [comment]
@adneg Try `binary.LittleEndian`?

**Comment by adneg** [comment]
@gordonklaus Yes it helped. it solved all my problems. Thank you very much.

**Comment by gordonklaus** [comment]
@adneg You're welcome 😄
