### ISSUE TITLE
Installing on MSYS2 gives error

### ISSUE THREAD

**Issue by kozie** [gordonklaus/portaudio#26]
I'm trying to install the Go Portaudio package on MSYS2. I installed the `mingw-w64-x86_64-portaudio` through pacman and got all the needed development tools to build, make, compile and what not.

Tho, when i try `go get github.com/gordonklaus/portaudio` i get the following error/output:

`go build github.com/gordonklaus/portaudio: invalid flag in pkg-config --cflags: -mthreads`

**Comment by gordonklaus** [comment]
portaudio-go uses CGO to wrap the underlying PortAudio C library.  CGO invokes pkg-config to find the appropriate flags to pass to the C compiler.  And apparently one of the flags in your portaudio-2.0.pc file is considered invalid by whatever C compiler you are using.  So I guess either your portaudio-2.0.pc file or your choice of C compiler needs to be adjusted.

[Apparently](https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/i386-and-x86_002d64-Options.html) the `-mthreads` flag should be recognized by GCC.  Are you using an old version that does not recognize the flag?

[This stackoverflow post](https://stackoverflow.com/questions/45243076/building-the-portaudio-golang-wrapper-on-windows) (esp. the comments) may lead to some help?

**Comment by kozie** [comment]
Thank you for your quick reply @gordonklaus .

I ended up building portaudio from source and following this comment https://www.reddit.com/r/golang/comments/5bl8vn/gowindowsaudio/d9pfdui/#t1_d9pfdui

Though, i think building from source is not necessary.
