### ISSUE TITLE
Determining FramesPerBuffer For Infinite Stream Time

### ISSUE THREAD

**Issue by UsersDoProgram** [gordonklaus/portaudio#27]
Currently I am working to record audio via the input device and send it through a TCP Conn to a client who will then use the same library to play the audio. Before I have tried to face the issue of piping the stream data to a socket I wanted to figure out how to approach the issue of streaming for an unknown or infinite amount of time. Programmatically how would I go about this process as some of the OpenDefaultStream requires a length of frames per buffer to be provided but how could that be done if I plan to stream data indefinitely between an input device through a socket connection to an output device on another machine with no time limit?

**Comment by UsersDoProgram** [comment]
@gordonklaus So I would put the the frame per buffer length as 44100 sample rate * 60 seconds for example and once recorded to empty the buffer and restart again?

**Comment by gordonklaus** [comment]
You should choose a buffer size depending on the responsiveness you want.  A minute-long buffer means you have to wait a whole minute before you receive any audio (i.e., very unresponsive).  For real-time audio filtering applications (e.g. live guitar effects) you would choose as small a buffer as possible.  If it doesn't really matter then you might go with [`FramesPerBufferUnspecified`](https://godoc.org/github.com/gordonklaus/portaudio#pkg-constants) (which I think only works for callback streams).

There is no "emptying of the buffer".  Your callback gets called when there is more audio to be recorded/played, or you call `Stream.Read`/`Write`.

Try out some of the [examples](https://github.com/gordonklaus/portaudio/tree/master/examples) to get a better idea for how things work.

**Comment by UsersDoProgram** [comment]
@gordonklaus Thank you for clarifying and I will definitely take a look at those examples.
