### ISSUE TITLE
Constant Beep When Playing Back Audio

### ISSUE THREAD

**Issue by UsersDoProgram** [gordonklaus/portaudio#28]
I wrote two files, one client and one server to send data via TCP and currently I got the connection to work but the issue is on the client end where the audio is played all you can hear is a beep I have no idea why this is an issue as everything seems right programmatically. The two files can be found here, 
[src.zip](https://github.com/gordonklaus/portaudio/files/2678437/src.zip). I tried applying the same process used in the examples but with slight modifications to fit the connection based method rather than using a file but as you can see I've had no luck.

**Comment by UsersDoProgram** [comment]
The file names are swapped, the client.go is the server and the server.go is the client.

**Comment by gordonklaus** [comment]
Sorry, but this isn't a general programming help hotline.  I'm happy to help out with any specific problems related to portaudio, but this seems more like an application-level problem.

Although it may be appropriate on some forums, in general it's kind of bad form to post your entire program code and ask someone to find the mistake.

My advice is that you test each part of your program independently to isolate the problem.  Good luck!
