### ISSUE TITLE
Compiling a static library

### ISSUE THREAD

**Issue by cor-bos** [gordonklaus/portaudio#32]
Hi,
I'm trying to compile a portaudio.dll but that gives me a lot of headache.
So I was wondering if threre's a way to compile a static go library instead of a shared one.
I'm not very familiar with the whole cgo process and my knowledge of c/c++ is very basic.
I know that rtaudio has a way to create a static go library.
Maybe someone can get me in the right direction to do it with go-portaudio
Regards,
Cor

**Comment by AllAwesome497** [comment]
Hey- I had this same issue, I made a [fork](https://github.com/AllAwesome497/portaudio/blob/master/README.md), This should work fine, if not feel free to create an issue on my fork.

**Comment by MagicalTux** [comment]
If you need I made a static version at https://github.com/KarpelesLab/static-portaudio ([doc](https://godoc.org/github.com/KarpelesLab/static-portaudio/portaudio))

It's the same go code as this repo, but embeds portaudio.
