### ISSUE TITLE
go binary references /usr/local/opt/portaudio/lib/libportaudio.2.dylib on mac

### ISSUE THREAD

**Issue by andrewarrow** [gordonklaus/portaudio#36]
Is there anyway to make it reference instead (or in addition to) the current path the binary is running from?

i.e. I could have in dir foo:

./libportaudio.2.dylib
./myapp

And running ./myapp it would find and use ./libportaudio.2.dylib before looking in /usr/local/opt/portaudio/lib/ ?

**Comment by missdeer** [comment]
`env DYLD_LIBRARY_PATH=$PWD ./myapp`
