### ISSUE TITLE
"Unknow Error" in MacOS Big Sur

### ISSUE THREAD

**Issue by elivoa** [gordonklaus/portaudio#41]
I update my mac to the latest system Big Sur
I installed portautio by 
```
brew install portaudio
```
when I run OpenDefaultStream, I got the following error:

```
"||PaMacCore (AUHAL)|| Error on line 1277: err='-66748', msg=Unknown Error"
```

but my pyhton code using pyaudio works fine.

Then I run `brew uninstall portaudio` and 
```brew install portaudio --HEAD```

the "Unknown Error" disappeared, but I got an Warrning!

```
ld: warning: directory not found for option '-L/usr/local/Cellar/portaudio/19.6.0/lib'
```

**Comment by gordonklaus** [comment]
I guess it's related to https://github.com/PortAudio/portaudio/issues/218?

Let's wait for that to get fixed.  After that, if the problem persists, feel free to re-open this issue or create a new one.
