### ISSUE TITLE
Playing Opus stream causes playback half speed

### ISSUE THREAD

**Issue by BigB84** [gordonklaus/portaudio#46]
Hi,
I'm writing an open-source Subsonic client in GO.

Inspired by mp3 example I tried to make a function that would stream opus data on demand. It almost worked but it plays in half speed. 

Assume that source file is 16bit 44100 stereo flac transcoded on the fly by server to same parameters opus but with lower 192 bitrate.

I tried to double sample rate but then it surprisingly plays 2x faster than normal... So I end with two times faster or two times slower playback

````go
import (
	"os"
	"os/signal"
	"strconv"

	"gopkg.in/hraban/opus.v2"
	"github.com/gordonklaus/portaudio"

)

const rate float64 = 44100
const seconds = 2
const channels = 2


func PlayOpusStream(){
       // get data
        sig := make(chan os.Signal, 1)
	signal.Notify(sig, os.Interrupt, os.Kill)
	nodeID, _ := MainQueue.Get(NowPlayingIndex)
	param := map[string]string{
		"maxBitRate":            "192",
		"MainFormat":            "opus",
		"transcodings":          "opus",
		"estimateContentLength": "true",
	}
	portaudio.Initialize()
	defer portaudio.Terminate()
	out := make([]int16, 192)
        //Create reader
	reader, err := CurrentClient.Stream(nodeID.(string), param)
	chk(err)
        // Make opus stream
	opusStr, err := opus.NewStream(reader)
	chk(err)
	stream, err := portaudio.OpenDefaultStream(0, 2, rate, cap(out), &out)
	chk(err)
	chk(stream.Start())
	for {
		_, err := opusStr.Read(out)
		if err == opus.ErrStreamEOF {
			return
		}
		chk(stream.Write())
		select {
		case <-sig:
			return
		default:
		}
	}
	chk(stream.Stop())
	defer stream.Close()
}


func chk(err error) {
	if err != nil {
		panic(err)
	}

}


````

The second problem is, that opus decoder has in its method []int16 or []float32 so I can't play like in mp3 example with byte[]...

Could you help me find any solution?
Thanks in advance :)

Cheers
Michael

**Comment by gordonklaus** [comment]
I could hazard a guess that you are receiving mono (single channel) audio and playing it stereo (two channel).  But that would only explain half speed, not double.

Try checking the first return value from `opusStr.Read` to see if it makes sense.

Where do you set the sample rate for the Subsonic client?  I only see `rate` passed to `portaudio.OpenDefaultStream`.

It's hard to say what the problem is since the code you've given is incomplete.  Can you provide more?

**Comment by BigB84** [comment]
Thanks for fast response :)

> Where do you set the sample rate for the Subsonic client? I only see rate passed to portaudio.OpenDefaultStream.

Oh sorry, I'll provide more code I forgot to add consts (I'll update first post code).

> Try checking the first return value from opusStr.Read to see if it makes sense.

Could you provide more details, I'm not so experienced yet... Sorry for such question

maybe the problem is in my ffmpeg transcoding command that is called on server every request that this client makes? 
`ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -c:a libopus -f opus -` where `%s` is source file and `%bk` is bitrate requested by client
I'm not sure if `map` is needed, but I haven't been digging into it yet.

**Comment by BigB84** [comment]
Ok, I'm so sorry, that was my fault...

I was surprised but sample rate changed while transcoding process (I tested and wrote stream to file that is normally passed to portaudio then checked its parameters with os media player). 

44100 flac became 48000 opus and as you can see above I pass rate from flac so it makes it play in incorrect speed. (So I heard that is too slow and guessed wrong that is half speed)

Again I'm sorry mess and for taking your time. Thanks for developing this great library :)
