### ISSUE TITLE
windows dll

### ISSUE THREAD

**Issue by fightforge** [gordonklaus/portaudio#51]
Hi,
I'm trying to include portaudio in my go project for windows, but when i run, it ask for libportaudio-2.dll
If i add the dll in the same folder of built exe it works, but i would to know if i can include the libportaudio-2.dll in the exe so that i can distribute it standalone.

Thanks

**Comment by gordonklaus** [comment]
Closing as a duplicate of #32.

**Comment by phanirithvij** [comment]
@gordonklaus can the changes made by MagicalTux [here](https://github.com/gordonklaus/portaudio/issues/32#issuecomment-735423834) be reviewed and ported to upstream?

**Comment by gordonklaus** [comment]
I don't think I'll find time any time soon to do the changes myself.  But I can review a PR and do some testing if someone else wants to do the work.

**Comment by dh1tw** [comment]
I honestly think that embedding the binary portaudio dll inside the library is rather an edge case. I would prefer not to have any binaries inside library.
