### ISSUE TITLE
How do I get microphone level? [HELP]

### ISSUE THREAD

**Issue by moigamijunior** [gordonklaus/portaudio#56]
Hi! I'm trying to get the stream audio level to know if someone is talking in the room.

I've tried to get `in` of StreamCallback, but I don't know how to convert the buffers to get the audio level. Can you help me?

```
func (e *echo) callback(in []float32) {
	for i := range in {
		// TODO
                // convert this input audio to get audio level
	}
}
```

In Python, I got [this piece of code](https://github.com/arupiot/Sound-level-meter/blob/master/slm.py) that works fine.

I've tried also to use a mat.Norm() from [gonum](https://github.com/gonum/gonum) library to normalize the incoming buffer, but I couldn't.

Thanks!

**Comment by gordonklaus** [comment]
This isn't the best place to ask such questions.  An audio/music forum would be more appropriate.

What you're looking for is RMS (root-mean-square) amplitude.  Google will give you many results.

**Comment by chapterjason** [comment]
@moigamijunior 

```go
func rms(samples []int16) float64 {
	var sum float64

	for _, sample := range samples {
		sum += float64(sample * sample)
	}

	mean := sum / float64(len(samples))

	return math.Sqrt(mean)
}
```
