### ISSUE TITLE
cross-compiling

### ISSUE THREAD

**Issue by rshmelev** [gordonklaus/portaudio#8]
Hi! I'm using MacOS, and would like to create app that works with microphone, ready-to-use on any platform (Windows, Linux, Mac)... so the question is - how to achieve this on my Mac?
Or... from any other OS (not a big deal to use Vagrant and build from there).

**Comment by helinwang** [comment]
just install portaudio with brew (or compile from source) and you can build the examples.

**Comment by rshmelev** [comment]
➜  examples git:(master) env GOOS=windows GOARCH=386 go build stereoSine.go
stereoSine.go:4:2: no buildable Go source files in /go/src/github.com/gordonklaus/portaudio

it is definitely able to build for mac, but it is not able to build for windows...
any suggestions?

**Comment by gordonklaus** [comment]
Sorry for the slow reply; somehow I was not watching my own repo :-/

Apparently cgo is disabled by default when cross-compiling.  You'll have to add CGO_ENABLED=1 to your command line.

**Comment by rshmelev** [comment]
Okay... still no luck :)
i wonder if i need to put somewhere some portaudio-for-windows headers or .lib files or whatever...

```
➜  examples git:(master) ✗ env CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build stereoSine.go
go build github.com/gordonklaus/portaudio: no buildable Go source files in /go/src/github.com/gordonklaus/portaudio
```

**Comment by gordonklaus** [comment]
Yeah, you will eventually need to have built portaudio for windows (which I'm afraid I can't help you with).  But at the moment that doesn't seem to be the problem.  Have you already verified that there actually are source files in `/go/src/github.com/gordonklaus/portaudio`?  To be honest you'll have a better chance resolving this, and faster, on golang-nuts; those folks are a helpful bunch.

**Comment by nkev** [comment]
@rshmelev Did you get this working? I'm having a nightmare trying to access portaudio in Windows from Go. I found portaudio [precompiled DLLs](https://github.com/spatialaudio/portaudio-binaries)  but still cannot get it to work on Windows.

**Comment by jdchum** [comment]
Definitely not an ideal solution, but I was able to get PortAudio working on Windows using the following procedures:

1. Compile or the appropriate DLL and move it into both your project's directory and the `portaudio` package directory
2. Modify the `cgo` directives in `portaudio.go` to the following:

```go
/*
#cgo LDFLAGS: -L${SRCDIR} -lportaudio
#include "portaudio.h"
extern PaStreamCallback* paStreamCallback;
*/
import "C"
```

In step 2, you can modify the path after `-L` and the library name after `-l` to match your desired library location and filename.

The reason this is a sloppy fix is because a) the dynamic library must be distributed with your compiled program or it won't work (statically linking might be better, still working that out) and b) it requires modification to the package source after downloading.

**Comment by BigB84** [comment]
Maybe it's time for docker? 
Big advantage is that you can also compile for other architectures like aarch64!
You may be interested in https://dh1tw.de/2019/12/cross-compiling-golang-cgo-projects/ tutorial _which really helped me._ It's step by step tutorial.

According to above, You could create `golang:1.17-bullseye` Dockerfile with architecture and compiler (for windows / linux of your choice)  _(as debian bullseye has multiarch support and multiarch libs)_  
However be careful with musl (glib alternative) lib linux distros like alpine linux according to [this](https://unix.stackexchange.com/questions/666559/crosscompile-golang-app-with-docker-for-alpine-linux-musl-aarch64-with-nativ)

**Comment by dh1tw** [comment]
I have explained in a blog post [how to cross compile golang cgo projects](https://dh1tw.de/2019/12/cross-compiling-golang-cgo-projects) using docker. You can find in a dedicated repository [the dockerfiles with the cross compiling toolchains setup for for several operating systems and architectures](https://github.com/dh1tw/remoteAudio-xcompile). The project [remoteAudio](https://github.com/dh1tw/remoteAudio) is actually using @gordonklaus's fantastic go binding for portaudio!

**Comment by talksik** [comment]
@dh1tw I tried your configuration but this is still a problem cross compiling from a mac m2 to linux for raspi using armhf
